apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
  name: node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: node-exporter
    spec:
      containers:
        - args:
            - --collector.arp.device-exclude
            - --collector.diskstats.device-exclude
            - --collector.ethtool.device-exclude
            - --collector.filesystem.fs-types-exclude
            - --collector.filesystem.mount-points-exclude
            - --collector.hwmon.chip-exclude
            - --collector.netdev.device-exclude
            - --collector.qdisk.device-exclude
            - --collector.systemd.unit-exclude
            - --collector.textfile.directory=/opt/textfile-collector
          name: node-exporter
          image: prom/node-exporter
          ports:
            - containerPort: 9100
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 180Mi
            requests:
              cpu: 102m
              memory: 180Mi
          volumeMounts:
            - mountPath: /opt/textfile-collector
              name: metric
              readOnly: true
      volumes:
        - name: metric
          configMap:
            defaultMode: 420
            name: metric
