apiVersion: v1
kind: Service
metadata:
  name: metric-analyzer
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: metric-analyzer
  sessionAffinity: None
  type: LoadBalancer
