apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# secrets have to be applied beforehand, see overlay/secrets

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
#  - git.secret.yaml # in prod

commonLabels:
  app.kubernetes.io/component: metricAnalyzer
