apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security-metric-analyzer-prometheus

resources:
  - pvc.yaml
  - clusterRole.yaml
  - namespace.yaml
  - metric.cm.yaml
  - prometheus-config-map.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml