apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: security-metric-analyzer-grafana

resources:
  - namespace.yaml
  - grafana.yaml
  - service.yaml
  - grafana-datasource-config.yaml
  - secret.yaml