apiVersion: v1
kind: Secret
metadata:
  name: metric-analyzer-secret
stringData:
  CONFLUENCE_URL: 'https://example.atlassian.net/wiki'  # change to your Confluence cloud URL
  CONFLUENCE_LOGIN: 'username@example.com'  # change to your account name/email
  CONFLUENCE_PASSWORD: ''  # fill in your API token from your Atlassian profile
